-- Q1 --
SELECT EMP_ID,EMP_NAME,PHONE,HIRE_DATE,ENT_YN
FROM employee
WHERE ENT_YN = 'N' AND
      PHONE LIKE '%2'
ORDER BY HIRE_DATE DESC
LIMIT 3;

-- Q2 --
# SELECT e.EMP_NAME, j.JOB_NAME, e.SALARY, e.EMP_ID, e.EMAIL, e.PHONE, e.HIRE_DATE
# FROM employee AS e, job AS j
# WHERE j.JOB_NAME = '대리'
# ORDER BY e.SALARY DESC;


